Final_Project_true_final-main/mci/views/fourth_test.py
from flask import Blueprint, render_template, request, redirect, url_for, session
import sqlite3

bp = Blueprint('fourth', __name__, url_prefix='/')

# 4th test
import random

@bp.route('/find_diff')
def find_diff():
    return render_template('4th_test.html')


#global 변수
# wrong_image_count = 0
# test_class = ['나비','지렁이','컴퓨터']
# test_key = ''
# # 밑에 next를 안 넣고 count>=3 을 하면 오류남 (인덱스 에러)/ 왜인진 모르겠지만 맨 마지막 인덱스는 안 나온다.-># 해결 
# wrong_ox = list() #db 저장용 
# html 렌더링
@bp.route('/wrong_img',  methods=['POST','GET'])
def wrong_img():
    # OX list에 결과값 저장
    wrong_ox = session['wrong_ox']
    wrong_image_count = session['wrong_image_count']
    test_key = session['test_key']
    test_class = session['test_class']

    if request.method == 'POST':
        image = str(request.form['button'])
        if 'X' in image:
            wrong_ox.append(1)
        else: wrong_ox.append(0)
    print(len(wrong_ox))
    print(wrong_image_count)
    # 이미지 불러오기
    if len(wrong_ox) != wrong_image_count:
        if len(wrong_ox) > 0:
            test_class.append(test_key)
        else:
            test_class = ['나비','지렁이','컴퓨터']
            wrong_image_count = len(wrong_ox)
    session['wrong_ox'] = wrong_ox
    # if len(test_class) == 0:
    #     test_class.append('나비')
    #     test_class.append('지렁이')
    #     test_class.append('컴퓨터')
    if wrong_image_count >=3 :
        session['wrong_image_count'] = 0 # 전역변수 횟수 0으로 바꿔주기
        return redirect(url_for('fourth.end')) # redirect를 할때는 route 옆에 오는 글자를 넣어줘야함(함수이름이 아님) 
    
    else:
        # 변수에 이미지 이름 넣기
        random.shuffle(test_class)
        session['test_key'] = test_class[0]
        img1 =test_class[0] + '1'
        img2=test_class[0] + '2'
        img3= test_class[0] + '3'
        img4= test_class[0] + 'X'
        # 랜덤으로 텍스트 보내기
        random_class =[img1,img2,img3,img4 ]
        random.shuffle(random_class)
        img1 = random_class[0]
        img2 = random_class[1]
        img3 = random_class[2]
        img4 = random_class[3]
        
        # 처음엔 for문으로 작성하려고 했으나 렌더링 될 때는 마지막 것만 되기 때문에 필요가 없음    
        # for i in test_class :   
        #     # str = test_class[i]    
        #     random_list = [i+'1', i+'2',i+'3',i+'X']
        #     random_list_2 = []
        #     random.shuffle(random_list)
        #     for  j in random_list:
        #         random_list_2.append(j)
        #     img1 = random_list_2[0]
        #     img2 = random_list_2[1]
        #     img3 = random_list_2[2]
        #     img4 = random_list_2[3]
            
        # 누른 버튼의 text 를 받아서 정답인지 오답인지 판별하기
        
        test_class.remove(test_class[0]) #  사용한 str 은 삭제해서 test_class 가 중복이 안되게 함.
        wrong_image_count += 1
        session['wrong_image_count'] = wrong_image_count
        return render_template('4th_test.html',img1 = img1, img2=img2,img3=img3,img4=img4) 
   

@bp.route('/end',  methods=['POST','GET'])
def end():
    # DB 저장 
    conn = sqlite3.connect('ijm.db', isolation_level=None)
    # 커서
    cursor = conn.cursor()
    # 테이블 생성(데이터 타입 = TEST, NUMERIC, INTEGER, REAL, BLOB(image) 등)
    # 필드명(ex. name) -> 데이터 타입(ex. text) 순서로 입력 
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS Wrong_Image (
        session TEXT PRIMARY KEY NOT NULL,
        game text,
        OX1 integer,
        OX2 integer,
        OX3 integer)""")
    
    # db 에 정보 저장
    game = 'Wrong_Image'
    wrong_ox = session['wrong_ox']
    OX1 = wrong_ox[0]
    OX2 = wrong_ox[1]
    OX3 = wrong_ox[2]
    guest = str(session['guest'])
    
    cursor.execute("""
        INSERT INTO Wrong_Image (session, game, OX1,OX2,OX3) VALUES (?,?,?,?,?)          
        """, (guest, game, OX1,OX2,OX3)
        )
    conn.commit()
    cursor.close()
    conn.close() 
    return render_template('5th_test.html')

Final_Project_true_final-main/mci/templates/0_intro.html
<!DOCTYPE html>
<html lang="ko">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>MIC</title>
        <!--stylesheet-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="{{ url_for('static', filename='css/styles/custom-responsive-styles.css') }}" rel = 'stylesheet'>
        <link href="{{ url_for('static', filename='css/styles/styles.css') }}" rel = 'stylesheet'>
        
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MIC</title>
    <style>
        body {background-image: url(../static/images/back1.JPG);
        background-repeat: no-repeat;
        background-size: cover};
        h1 {font-family: 'Times New Roman', Times, serif; padding: 7px;}
        li {font-weight: bolder; list-style: none; font-size : 15px}
        span {font-weight: lighter;}

   
          #image-container {
            position: fixed;
            bottom: 40px;
            right: 40px;
          }
          #image-container img {
            width: 150px;
            height: 150px;
          }
          #speech-bubble {
            display: none;
            position: absolute;
            bottom: 140px;
            right: 20px;
            top: -115px;
            background-color: #fff;
            padding: 10px;
            border-radius: 10px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
          }
          
          #image-container:hover #speech-bubble {
            display: block;
          }

          #image-container1 {
            position: fixed;
            bottom: 40px;
            left: 40px;
          }
          #image-container1 img {
            width: 150px;
            height: 150px;
          }
          #speech-bubble1 {
            display: none;
            position: absolute;
            bottom: 140px;
            right: 20px;
            top: -115px;
            background-color: #fff;
            padding: 10px;
            border-radius: 10px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
          }
          
          #image-container1:hover #speech-bubble1 {
            display: block;
          }

      
    </style>
    
</head>

<body>
<a href="/" style="width: 100px;">
<br><img src="{{ url_for('static', filename = 'img/logo2.png')}}" alt="Image" style="width: 105px;"></a>
    <br>
    <h1 align="center"> 경도 인지저하 테스트</h1>
    <div id="image-container">
      <img src="{{ url_for('static', filename = 'face/Jieun.png')}}" alt="Image">
      <div id="speech-bubble">
        <center><p>이제<br> 긴장을 풀고 시작해볼까?</p>
      </div>
    </div>
    <div id="image-container1">
      <img src="{{ url_for('static', filename = 'face/heehyun.png')}}" alt="Image">
      <div id="speech-bubble1">
        <center><p>과연<br> 전부 다<br> 할 수 있을까?</p>
      </div>
    </div>
    <br>
        <div style="border: px solid; padding :10px; width: 820px; 
        height: 540px ; border-radius:2em; margin:auto; 
        padding-top:50px; background-color:rgba(255, 255, 255, 0.744) ">

                       <!--모델-->
                       <br>
    <h1 align="center">Before Test</h1><br><center>
      <br>
        <div class="row justify-content-center text-center mb-5"><p><b>
      👀 이 테스트는 한국판 몬트리올 인지평가(MoCA-K)를 바탕으로 제작되었습니다<br><br>
      ⏰ 10분정도 소요됩니다<br><br>
      👌 주의력, 집중력, 실행력, 기억력, 추상력, 지남력과 같은 인지기능을 평가합니다<br><br>
      💻 컴퓨터를 다루는데 서투른 경우에는 권장하지 않습니다<br><br>
      </div>
                        <!--모델 끝-->
      
        </div>
    <h2>
        <div>
            <center>
                <br>
                <input type="button" value="시작하기" style="
                width: 180px; height:100; padding-top:12px; padding-bottom:12px;
                border-radius:15px; cursor : pointer ;  font-size:19px; 
                font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-weight:bolder;  color:rgb(0, 0, 0);" onClick="window.location.href='/vgg'">
            </center>
        </div>
    </h2>
    <h3>
        <form align="center">
            <center>
                <div style="border: 2px solid; padding :10px; height: 85px; width: 180px;
                    padding-top:7px; background-color:rgba(255, 255, 255, 0.455);">
                    <p style="margin-top:1px; margin-bottom: 10px; font-size:26px; ""> provided by<br> Team.인절미</p>
                </div>
            </center>    
        </form>  
    </h3>
    <br>
    <br>
</section>

<footer class="footer text-center">
    <div class="container">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white" href="javascript:void(0)">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
        </li>
      </ul>
      <p class="text-muted small mb-0">Copyright © Your Website 2018</p>
      <p class="text-muted small mb-0">Designed by <a href="https://www.position2.com/" target="_balnk">Position2</p>
    </div>
  </footer>
  

<!--scripts-->
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/jquery-3.2.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/all-plugins.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/plugins-activate.js') }}"></script>
</body>
</html>

Final_Project_true_final-main/mci/templates/1st_test.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=0.1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon-32x32.png') }}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon-16x16.png') }}" sizes="16x16" />
  <title>MCI</title>
  <!--stylesheet-->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/styles.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/custom-responsive-styles.css') }}"
    type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/huiyacanvars.css') }}" type="text/css">


  <style>
    body {background-image: url(../static/images/back2.JPG);
      background-repeat: no-repeat;
      background-size: cover};

    h1 {
      font-family: 'Times New Roman', Times, serif;
      padding: 7px;
    }

    li {
      font-weight: bolder;
      list-style: none;
      font-size: 15px
    }

    span {
      font-weight: lighter;
    }

    .controls__btns {
      display: flex;
      justify-content: center;
    }
      #image-container {
        position: fixed;
        bottom: 10px;
        right: 10px;
        width: 200px;
        height: 200px;
        background: transparent;
      }
      #image-container img {
        width: 150px;
        height: 150px;
        cursor: pointer;
      }
      #speech-bubble {
        display: none;
        position: absolute;
        bottom: 180px;
        right: 20px;
        top: -105px;
        background-color: #fff;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
      }
      
      #image-container:hover #speech-bubble {
        display: block;
      }

      #image-container1 {
        position: fixed;
        bottom: 80px;
        left: 100px;
      }
      #image-container1 img {
        width: 150px;
        height: 150px;
      }
      #speech-bubble1 {
        display: none;
        position: absolute;
        bottom: 120px;
        top: -300px;
        background-color: #fff;
        padding: 10px;
        border-radius: 10px;
        box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
        display: block;
        width: 200px;
      }
      
      #image-container1:hover #speech-bubble1 {
        display: block;
      }
  </style>

</head>

<body>
  <a href="/" style="width: 100px;">
    <br><img src="{{ url_for('static', filename = 'img/logo2.png')}}" alt="Image" style="width: 105px;"></a>
  <h1 align="center">  비슷한 그림 그리기 </h1>
  <h6>
    <p style="text-align:center;">5초동안 그림을 잘 기억한 후 최대한 비슷하게 그려주세요<br>다 그린 후 제출 버튼을 누르고 다음으로 넘어가세요
  </h6>
  <div id="image-container">
    <img src="{{ url_for('static', filename = 'face/dongwhan.png')}}" alt="Image">
    <div id="speech-bubble">
      <center><p>잘 그리지 않아도 돼!<br> 특징적인 부분을<br> 그려봐</p>
    </div>
  </div>
  <div id="image-container1">
    <img src="{{ url_for('static', filename = 'img/drawing.png')}}" alt="Image" style="width: 110px; height: auto;">
    <div id="speech-bubble1">
      <p style="text-align:center;"><strong><center><p>전두엽<br>측두엽<br>후두엽<br>🧠<br>시각적 학습<br>기하학적 모양에 대한 기억력<br>즉각/지연 상기<br>소근육 조절</p>
    </div>
  </div>
  <div class='container'>
    <div style="border: px solid; padding :10px; width: 820px; 
    height: 540px ; border-radius:2em; margin:auto; 
    padding-top:50px; background-color:#fff ">
      <div>
        <center>
          <img id="image" src={{h_path}} style="display: none;" width=450>
        </center>
      </div>

      <!--그림판-->
      <!-- <div>
        <canvas id="jsCanvas" class="canvas" style="display:none;"></canvas>
        <center>
      </div>
      
      <div class="controls__btns" style="display: flex; justify-content: center;">
        <button id="jsBrush">브러쉬</button>
        <button id="jsAllremove">전체지우기</button>
        <button id="jsSubmitButton">제출</button>
      </div>
      </center> -->

      <center>
        <canvas id="jsCanvas" class="canvas"></canvas>
      </center>
      <!-- 브러쉬 -->
      <div class="controls">
        <div class="controls__range" id="jsRange" value="2.5">
        </div>
        <!-- 팬 색 -->
        <div class="controls__color jsColor" style="background-color: #2c2c2c"></div>
      </div>
      <center>
        
      
        <div class="controls__btns">
          <button id="jsMode">Fill</button>
          <button id="move-btn" type='submit' value="move-btn" >Save</button>
          <button id="jsReset">Reset</button>
          <button id="jsSave">저장</button>
          
        </div>
      </center>
    </div>
  </div>
  <!--그림판 끝-->
  <script>
    document.getElementById("image").style.display = "block";
    document.getElementById('jsCanvas').style.display = 'none';
    document.getElementById('jsMode').style.display = 'none'
    document.getElementById('move-btn').style.display = 'none';
    document.getElementById('jsReset').style.display = 'none';
    document.getElementById('jsSave').style.display = 'none';

    setTimeout(function () {
      document.getElementById("image").style.display = "none";
    }, 5000);

    setTimeout(function () {
      document.getElementById("jsCanvas").style.display = "block";
    }, 5000);

    setTimeout(function () {
      document.getElementById("jsMode").style.display = "none";
    }, 5000);

    setTimeout(function () {
      document.getElementById("move-btn").style.display = "flex";
    }, 5000);

    setTimeout(function () {
      document.getElementById("jsReset").style.display = "flex";
    }, 5000);

    setTimeout(function () {
      document.getElementById("jsSave").style.display = "none";
    }, 5000);

    document.getElementById("move-btn").addEventListener("click", function () {
      let canvas = document.getElementById("jsCanvas");
      let dataURL = canvas.toDataURL();
      let blob = dataURLToBlob(dataURL);
      let formData = new FormData();
      formData.append("image", blob, "image.png");
      let xhr = new XMLHttpRequest();
      xhr.open("POST", "/image_similarity", true);
      xhr.send(formData);
      xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
          window.location.href = "/stroop";
        }
      };
    }
    );

    function dataURLToBlob(dataURL) {
      let parts = dataURL.split(";base64,");
      let contentType = parts[0].split(":")[1];
      let raw = window.atob(parts[1]);
      let rawLength = raw.length;
      let uInt8Array = new Uint8Array(rawLength);
      for (let i = 0; i < rawLength; ++i) {
        uInt8Array[i] = raw.charCodeAt(i);
      }
      return new Blob([uInt8Array], { type: contentType });
    }
  </script>

  </div>
  <h2>
    <div>
      <center>
        <br>
        <input type="button" value="다음으로 넘어가기" style="
                width: 180px; height:100; padding-top:12px; padding-bottom:12px;
                border-radius:15px; cursor : pointer ;  font-size:19px; 
                font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-weight:bolder;  color:rgb(0, 0, 0); " onClick="location.href='/stroop'">
      </center>
    </div>
  </h2>
  <h3>
    <form align="center">
      <center>
        <div style="border: 2px solid; padding :10px; height: 85px; width: 200px;
                    padding-top:7px; background-color:rgba(255, 255, 255, 0.455);">
          <p style="margin-top:1px; font-size:26px; ""> provided by<br> Team.인절미</p>
        </div>
      </center>
    </form>
  </h3>
  </div>
  <br>
  <br>
  </section>

  <footer class="footer text-center">
    <div class="container">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white" href="javascript:void(0)">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
          </a>
        </li>
      </ul>
      <p class="text-muted small mb-0">Copyright © Your Website 2018</p>
      <p class="text-muted small mb-0">Designed by <a href="https://www.position2.com/" target="_balnk">Position2</p>
    </div>
  </footer>

  <!--scripts-->
  <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/all-plugins.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/plugins-activate.js') }}"></script>
  <script src="{{ url_for('static', filename='js/canvas.js') }}"></script>
</body>

</html>

Final_Project_true_final-main/mci/templates/4th_test.html
<!DOCTYPE html>
<html lang="ko">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=0.1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" type="image/PNG" href="../static/images/favicon-32x32.PNG" sizes="32x32" />
        <link rel="icon" type="image/PNG" href="../static/images/favicon-16x16.PNG" sizes="16x16" />
        <title>MIC</title>
        <!--stylesheet-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/styles.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/custom-responsive-styles.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles/huiyacanvars.css') }}" type="text/css">

    <title>MIC</title>
    <style>
        body {background-image: url(../static/images/back5.JPG);
            background-repeat: no-repeat;
            background-size: cover};
        h1 {font-family: 'Times New Roman', Times, serif; padding: 7px;}
        li {font-weight: bolder; list-style: none; font-size : 15px}
        span {font-weight: lighter;}
    </style>
</head>
<body>
    <a href="/" style="width: 100px;">
        <br><img src="{{ url_for('static', filename = 'img/logo2.png')}}" alt="Image" style="width: 105px;"></a>
    <br>
    <h1 align="center"> 다른 그림 찾기 </h1>
    <h5><p style="text-align:center;">다음 보기 중에 다른 것을 고르세요</h5>
        <div id="image-container">
            <img src="{{ url_for('static', filename = 'face/jiyoung.png')}}" alt="Image">
            <div id="speech-bubble">
                <center><p>혼자<br> 특성이 다른 걸<br> 고르면 돼</p>
            </div>
          </div>
          <div id="image-container1">
            <img src="{{ url_for('static', filename = 'img/thinking.png')}}" alt="Image" style="width: 110px; height: auto;">
            <div id="speech-bubble1">
              <p style="text-align:center;"><strong><center><p>측두엽<br>후두엽<br>🧠<br>시각적 학습<br>선택 반응 시간<br>즉각적인 의사결정</p>
            </div>
          </div>
          <style>
            #image-container {
              position: fixed;
              bottom: 10px;
              right: 10px;
              width: 200px;
              height: 200px;
              background: transparent;
            }
            #image-container img {
              width: 150px;
              height: 150px;
              cursor: pointer;
            }
            #speech-bubble {
              display: none;
              position: absolute;
              bottom: 180px;
              right: 20px;
              top: auto;
              background-color: #fff;
              padding: 10px;
              border-radius: 10px;
              box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
            }
            
            #image-container:hover #speech-bubble {
              display: block;
            }
            #image-container1 {
              position: fixed;
              bottom: 80px;
              left: 100px;
            }
            #image-container1 img {
              width: 150px;
              height: 150px;
            }
            #speech-bubble1 {
              display: none;
              position: absolute;
              bottom: 120px;
              top: -220px;
              background-color: #fff;
              padding: 10px;
              border-radius: 10px;
              box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
              display: block;
              width: 200px;
            }
            
            #image-container1:hover #speech-bubble1 {
              display: block;
            }
          </style>
    <br>
        <div style="border: px solid; padding :10px; width: 820px; 
        height: 490px ; border-radius:2em; margin:auto; 
        padding-top:50px; background-color:rgb(255, 255, 255) ">
                       <!--모델-->

                       
                       <form action="{{ url_for('fourth.wrong_img') }}" method="POST">
                       <div class="container4">
                        <div class="row">
                            <div class="col-12 d-flex justify-content:center;">
                                <div class="card m-3" >
                                    <img class="card-img-top" src = "{{url_for('static', filename = '4/img/'+ img1 +'.PNG')}}" alt="image1" >
                                    <div class="card-body d-flex align-items-center">
                                        <button id="button" name="button" class="btn btn-primary" value= '{{img1}}' type="submit">Button 1</button>
                                    </div>
                                </div>
                                <div class="card m-3" >
                                    <img class="card-img-top" src="{{url_for('static', filename = '4/img/' + img2 +'.PNG')}}" alt="image2" >
                                    <div class="card-body d-flex align-items-center">
                                        <button id="button" name="button" class="btn btn-primary" value= '{{img2}}' type="submit">Button 2</button>
                                    </div>
                                </div>
                                <div class="card m-3" >
                                    <img class="card-img-top" src="{{url_for('static', filename = '4/img/' + img3 +'.PNG')}}" alt="image3" >
                                    <div class="card-body d-flex align-items-center">
                                        <button id="button"name="button" class="btn btn-primary" value= '{{img3}}' type="submit">Button 3</button>   
                                    </div>
                                </div>
                                <div class="card m-3" >
                                    <img class="card-img-top" src="{{url_for('static', filename = '4/img/' + img4 +'.PNG')}}" alt="image4" >
                                    <div class="card-body d-flex align-items-center">
                                        <button id="button" name="button" class="btn btn-primary" value= '{{img4}}' type="submit">Button 4</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  
                    
                      
                    <!--모델-->
      
        </div>
    <h2>
        <div>
            <center>
                <br>
                <input type="button" value="다음으로 넘어가기" style="
                width: 180px; height:100; padding-top:12px; padding-bottom:12px;
                border-radius:15px; cursor : pointer ;  font-size:20px; 
                font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-weight:bolder;  color:rgb(0, 0, 0); "onClick="window.location.href='/pygame'">
            </center>
        </div>
    </h2>
    <h3>
        <form align="center">
            <center>
                <div style="border: 2px solid; padding :10px; height: 85px; width: 180px;
                    padding-top:7px; background-color:rgba(255, 255, 255, 0.455);">
                    <p style="margin-top:1px; font-size:26px;"> provided by<br> Team.인절미</p>
                </div>
            </center>    
        </form>  
    </h3>
    <br>
    <br>
</section>
<footer class="footer text-center">
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item">
        <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </a>
      </li>
      <li class="list-inline-item">
        <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
      </li>
      <li class="list-inline-item">
        <a class="social-link rounded-circle text-white" href="javascript:void(0)">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
          </a>
      </li>
    </ul>
    <p class="text-muted small mb-0">Copyright © Your Website 2018</p>
    <p class="text-muted small mb-0">Designed by <a href="https://www.position2.com/" target="_balnk">Position2</p>
  </div>
</footer>

       <!--scripts-->
       <!--<script type="text/javascript" src="{{ url_for('static', filename='js/4_java.js') }}"></script>-->
       <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
       <script type="text/javascript" src="{{ url_for('static', filename='js/all-plugins.js') }}"></script>
       <script type="text/javascript" src="{{ url_for('static', filename='js/plugins-activate.js') }}"></script>

</body>
</html>